//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.05 at 11:24:28 AM EDT 
//


package com.boredatlunch.whatsforlunch.Model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.boredatlunch.whatsforlunch.Model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.boredatlunch.whatsforlunch.Model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Results.Locations }
     * 
     */
    public Results.Locations createResultsLocations() {
        return new Results.Locations();
    }

    /**
     * Create an instance of {@link Results.Locations.Location.Address }
     * 
     */
    public Results.Locations.Location.Address createResultsLocationsLocationAddress() {
        return new Results.Locations.Location.Address();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link Results.Locations.Location }
     * 
     */
    public Results.Locations.Location createResultsLocationsLocation() {
        return new Results.Locations.Location();
    }

    /**
     * Create an instance of {@link Results.Locations.Location.Tags.Tag }
     * 
     */
    public Results.Locations.Location.Tags.Tag createResultsLocationsLocationTagsTag() {
        return new Results.Locations.Location.Tags.Tag();
    }

    /**
     * Create an instance of {@link Results.Locations.Location.Tags }
     * 
     */
    public Results.Locations.Location.Tags createResultsLocationsLocationTags() {
        return new Results.Locations.Location.Tags();
    }

}
